version: '3.1'

services:
  db:
    build: ./db
    container_name: scraper-postgres
    restart: always
    ports:
      - "5435:5432"

  scraper:
    build: ./
    container_name: scraper
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  bayes:

    build: ./bayes
    container_name: scraper-bayes
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db